version: '3'
services:
  gwcchatbot:
    container_name: 'gwcchatbot'
    restart: on-failure
    build: .
    command: nodemon --watch . -e js,html -L app/index.js
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app:delegated
      - ./package.json:/opt/package.json
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_modules location.
      - notused:/opt/app/node_modules
volumes:
  notused: